version: "3.9"

services:
  neo4j:
    build:
      dockerfile: ./neo4j.Dockerfile
    environment:
      NEO4J_AUTH: neo4j/12344321
    ports:
      - "7474:7474"
      - "7687:7687"
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s
