name: Setup Rust
description: "Action used to setup the rust environment"

runs:
  using: composite
  steps:
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Install rust stable
      uses: dtolnay/rust-toolchain@stable
      with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

    - uses: taiki-e/install-action@nextest
